/*CC = g++
CFLAGS = `pkg-config --cflags opencv4` -I headers/
LIBS = `pkg-config --libs opencv4`

SRC = src/main.cpp src/gvfc.cpp src/common.cpp src/drlse_edge.cpp
OBJ = active_contour_demo
program: 
	$(CC) -o $(OBJ) $(SRC) $(CFLAGS) $(LIBS) -lstdc++ -lm
